version: "3.3"
services:
  jekyll:
    image: jekyll/jekyll
    container_name: jekyll
    ports:
      - 4000:4000
    environment:
      - JEKYLL_ENV=development
    volumes:
      - .:/srv/jekyll:cached
      - ./vendor/bundle/:/usr/local/bundle:cached
    restart: always
    command: jekyll serve --force_polling -drafts
